name: J-code Analyzer

on:
  push:
    branches: [ "main" ]  # Запускать при каждом push в ветку main
  pull_request:
    branches: [ "main" ]  # Также можно запускать при pull request

jobs:
  analyze:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Проверяем код из репозитория

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Указываем версию Python

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run J-code analyzer
      run: |
        python main.py
